"use client";

import { Building2, Mail, Search, Store, UserPlus, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api, RequestError } from "../../../lib/api";
import { Alert } from "../../../components/ui/alert";
import { Badge } from "../../../components/ui/badge";
import { Button } from "../../../components/ui/button";
import { ConfirmDialog } from "../../../components/ui/confirm-dialog";
import { EmptyState } from "../../../components/ui/empty-state";
import { Input } from "../../../components/ui/input";
import { Label } from "../../../components/ui/label";
import { Modal } from "../../../components/ui/modal";
import { PageHeader } from "../../../components/ui/page-header";
import { Skeleton } from "../../../components/ui/skeleton";

interface UserRow { id: string; displayName: string; email: string; role: string; status: string; invitation: { pending: boolean }; assignments: Array<{ shopId: string; shopName: string; startedAt: string; endedAt: string | null; reason: string | null }> }
interface ShopRow { id: string; name: string; status: string }
const selectClass = "h-10 w-full rounded-md border border-[var(--separator)]/70 bg-[var(--surface-subtle)] px-3 text-sm outline-none transition-colors focus-visible:border-[var(--focus)] focus-visible:ring-1 focus-visible:ring-[color-mix(in_srgb,var(--focus)_35%,transparent)]";

export default function UsersPage() {
  const [users, setUsers] = useState<UserRow[] | null>(null); const [shops, setShops] = useState<ShopRow[]>([]); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const [email, setEmail] = useState(""); const [displayName, setDisplayName] = useState(""); const [reason, setReason] = useState(""); const [selectedUser, setSelectedUser] = useState(""); const [selectedShop, setSelectedShop] = useState(""); const [query, setQuery] = useState("");
  const [pending, setPending] = useState(false); const [inviteOpen, setInviteOpen] = useState(false); const [assignOpen, setAssignOpen] = useState(false); const [confirm, setConfirm] = useState<"assign" | "deactivate" | null>(null); const [targetUser, setTargetUser] = useState("");
  async function reload() { const [userData, shopData] = await Promise.all([api<{ users: UserRow[] }>("/api/v1/users"), api<{ shops: ShopRow[] }>("/api/v1/shops")]); setUsers(userData.users); setShops(shopData.shops); }
  useEffect(() => { reload().catch((caught: RequestError) => setError(caught.message)); }, []);
  const visibleUsers = useMemo(() => { const normalized = query.trim().toLowerCase(); if (!normalized) return users ?? []; return (users ?? []).filter((user) => { const current = user.assignments.find((item) => !item.endedAt); return `${user.displayName} ${user.email} ${current?.shopName ?? ""}`.toLowerCase().includes(normalized); }); }, [query, users]);
  const managers = (users ?? []).filter((user) => user.role === "MANAGER" && user.status !== "DISABLED");
  const availableManagers = managers.filter((user) => !user.assignments.some((item) => !item.endedAt));
  const assignedManagers = managers.filter((user) => user.assignments.some((item) => !item.endedAt)).length;
  const pendingInvitations = (users ?? []).filter((user) => user.invitation.pending).length;
  if (error) return <Alert tone="error">{error}</Alert>;
  if (!users) return <Skeleton className="h-48" />;

  return <section className="space-y-6">
    <PageHeader title="Équipe et accès" action={<div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!shops.length || !availableManagers.length} onClick={() => setAssignOpen(true)}><Building2 className="size-4" /> Affecter</Button><Button onClick={() => setInviteOpen(true)}><UserPlus className="size-4" /> Inviter un gérant</Button></div>}>Gérez les accès nominatifs et le responsable de chaque boutique.</PageHeader>
    {success ? <Alert tone="success">{success}</Alert> : null}
    <div className="grid overflow-hidden rounded-lg bg-[var(--surface)] shadow-[var(--shadow-card)] sm:grid-cols-3"><Metric value={managers.length} label={`gérant${managers.length > 1 ? "s" : ""}`} /><Metric value={assignedManagers} label={`affecté${assignedManagers > 1 ? "s" : ""} à une boutique`} bordered /><Metric value={pendingInvitations} label={`invitation${pendingInvitations > 1 ? "s" : ""} en attente`} bordered /></div>
    <section><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-display text-lg font-semibold">Membres</h2><p className="text-sm text-[var(--muted)]">{users.length} compte{users.length > 1 ? "s" : ""} dans votre organisation</p></div><label className="relative w-full sm:max-w-sm"><span className="sr-only">Rechercher un membre</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--muted)]"/><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nom, e-mail ou boutique" /></label></div>
      {!visibleUsers.length ? <EmptyState icon={<UsersRound />} title="Aucun membre trouvé">{query ? "Modifiez votre recherche." : "Invitez un premier gérant pour préparer une boutique."}</EmptyState> : <div className="overflow-hidden rounded-lg bg-[var(--surface)] shadow-[var(--shadow-card)]"><div className="hidden grid-cols-[minmax(240px,1.4fr)_minmax(170px,0.8fr)_110px_150px] gap-4 bg-[var(--surface-subtle)] px-5 py-2.5 text-xs font-semibold uppercase tracking-wide text-[var(--muted)] md:grid"><span>Membre</span><span>Affectation</span><span>Statut</span><span className="text-right">Actions</span></div><ul className="divide-y divide-[var(--separator)]/60">{visibleUsers.map((user) => <MemberRow key={user.id} user={user} pending={pending} onReload={reload} onSuccess={setSuccess} onError={setError} onPending={setPending} onAssign={(current) => { setSelectedUser(user.id); setSelectedShop(current?.shopId ?? ""); setReason(current ? "Changement d’affectation" : "Responsable de boutique"); setAssignOpen(true); }} onDeactivate={() => { setTargetUser(user.id); setReason(""); setConfirm("deactivate"); }} />)}</ul></div>}
    </section>
    <Modal open={inviteOpen} onOpenChange={setInviteOpen} title="Inviter un gérant" description="Créez un accès nominatif. Vous pourrez ensuite l’affecter à une boutique." size="sm"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setPending(true); setSuccess(null); api("/api/v1/users", { method: "POST", body: JSON.stringify({ email, displayName }) }).then(() => { setEmail(""); setDisplayName(""); setInviteOpen(false); setSuccess("Invitation créée."); return reload(); }).catch((caught: RequestError) => setError(caught.message)).finally(() => setPending(false)); }}><Field id="invite-name" label="Nom complet" value={displayName} onChange={setDisplayName} placeholder="Ex. Amina Njoya" /><Field id="invite-email" label="Adresse e-mail" type="email" value={email} onChange={setEmail} placeholder="amina@entreprise.com" /><ModalActions cancel={() => setInviteOpen(false)} pending={pending} label="Créer l’invitation" /></form></Modal>
    <Modal open={assignOpen} onOpenChange={setAssignOpen} title="Affecter un gérant" description="Choisissez le responsable et la boutique concernés." size="sm">{!shops.length ? <EmptyState icon={<Store />} title="Aucune boutique">Créez une boutique avant d’affecter un gérant.</EmptyState> : <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setConfirm("assign"); }}><div className="space-y-1.5"><Label htmlFor="assign-user">Gérant</Label><select id="assign-user" className={selectClass} required value={selectedUser} onChange={(event) => setSelectedUser(event.target.value)}><option value="">Choisir un gérant</option>{availableManagers.map((user) => <option key={user.id} value={user.id}>{user.displayName}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="assign-shop">Boutique</Label><select id="assign-shop" className={selectClass} required value={selectedShop} onChange={(event) => setSelectedShop(event.target.value)}><option value="">Choisir une boutique</option>{shops.map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></div><Field id="assign-reason" label="Motif de l’affectation" value={reason} onChange={setReason} placeholder="Ex. Responsable principal" /><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={() => setAssignOpen(false)}>Annuler</Button><Button type="submit" disabled={pending || !selectedUser || !selectedShop}>Vérifier</Button></div></form>}</Modal>
    <ConfirmDialog open={confirm === "assign"} onOpenChange={(open) => setConfirm(open ? "assign" : null)} title="Confirmer l’affectation" confirmLabel="Confirmer" pending={pending} onConfirm={() => { setPending(true); api(`/api/v1/shops/${selectedShop}/assign-manager`, { method: "POST", body: JSON.stringify({ userId: selectedUser, reason }) }).then(() => { setSuccess("Affectation enregistrée."); setConfirm(null); setAssignOpen(false); setSelectedUser(""); setSelectedShop(""); setReason(""); return reload(); }).catch((caught: RequestError) => setError(caught.message)).finally(() => setPending(false)); }}>Le gérant sélectionné deviendra le responsable actif. L’affectation précédente restera dans l’historique.</ConfirmDialog>
    <ConfirmDialog open={confirm === "deactivate"} onOpenChange={(open) => setConfirm(open ? "deactivate" : null)} title="Désactiver ce compte" confirmLabel="Désactiver" tone="danger" pending={pending} onConfirm={() => { if (reason.trim().length < 3) { setError("Le motif est obligatoire."); return; } setPending(true); api(`/api/v1/users/${targetUser}/deactivate`, { method: "POST", body: JSON.stringify({ reason }) }).then(() => { setSuccess("Compte désactivé."); setConfirm(null); return reload(); }).catch((caught: RequestError) => setError(caught.message)).finally(() => setPending(false)); }}><Field id="deactivate-reason" label="Motif obligatoire" value={reason} onChange={setReason} /></ConfirmDialog>
  </section>;
}

function Metric({ value, label, bordered = false }: { value: number; label: string; bordered?: boolean }) { return <div className={`${bordered ? "border-t border-[var(--separator)]/60 sm:border-l sm:border-t-0" : ""} p-4`}><p className="text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-sm text-[var(--muted)]">{label}</p></div>; }
function Field({ id, label, value, onChange, type = "text", placeholder }: { id: string; label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <div className="space-y-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} required minLength={type === "email" ? undefined : 2} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></div>; }
function ModalActions({ cancel, pending, label }: { cancel: () => void; pending: boolean; label: string }) { return <div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={cancel}>Annuler</Button><Button type="submit" disabled={pending}>{pending ? "Traitement…" : label}</Button></div>; }

function MemberRow({ user, pending, onReload, onSuccess, onError, onPending, onAssign, onDeactivate }: { user: UserRow; pending: boolean; onReload: () => Promise<void>; onSuccess: (value: string) => void; onError: (value: string) => void; onPending: (value: boolean) => void; onAssign: (current?: UserRow["assignments"][number]) => void; onDeactivate: () => void }) {
  const current = user.assignments.find((item) => !item.endedAt);
  return <li className="grid gap-3 px-5 py-4 md:grid-cols-[minmax(240px,1.4fr)_minmax(170px,0.8fr)_110px_150px] md:items-center md:gap-4"><div className="flex min-w-0 items-center gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-[var(--surface-subtle)] text-sm font-semibold text-[var(--primary)]">{user.displayName.slice(0, 1).toUpperCase()}</div><div className="min-w-0"><p className="truncate font-semibold">{user.displayName}</p><p className="mt-0.5 flex items-center gap-1.5 truncate text-sm text-[var(--muted)]"><Mail className="size-3.5 shrink-0" />{user.email}</p></div></div><div><p className="text-sm font-medium">{user.role === "OWNER" ? "Administration générale" : current?.shopName ?? "Sans boutique"}</p>{user.role === "MANAGER" ? <p className="mt-0.5 text-xs text-[var(--muted)]">{current ? "Responsable actuel" : "Disponible"}</p> : null}</div><div><Badge>{user.invitation.pending ? "Invité" : user.status === "ACTIVE" ? "Actif" : user.status === "DISABLED" ? "Désactivé" : user.status}</Badge></div><div className="flex flex-wrap justify-start gap-1 md:justify-end">{user.invitation.pending ? <Button className="h-8 px-2.5" variant="secondary" disabled={pending} onClick={() => { onPending(true); api(`/api/v1/users/${user.id}/resend-invitation`, { method: "POST" }).then(() => { onSuccess("Invitation renvoyée."); return onReload(); }).catch((caught: RequestError) => onError(caught.message)).finally(() => onPending(false)); }}>Renvoyer</Button> : null}{user.role === "MANAGER" && user.status !== "DISABLED" && !current ? <Button className="h-8 px-2.5" variant="ghost" onClick={() => onAssign(current)}>Affecter</Button> : null}{user.role === "MANAGER" && user.status !== "DISABLED" ? <Button className="h-8 px-2.5 text-[var(--destructive)]" variant="ghost" onClick={onDeactivate}>Désactiver</Button> : null}</div></li>;
}
